### ISSUE TITLE
ndex package does not install from pip due to missing README.md

### ISSUE THREAD

**Issue by johnbachman** [ndexbio/ndex-python#1]
When I try to install the ndex package from PyPi using pip I get an error due to the fact that setup.py attempts to read the package description from the README.md file, and README.md is not included in the release.

Here's the output:

```
$ pip install ndex
Collecting ndex
  Using cached ndex-3.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1x/qf_k0tln39l637nj4jzrytgh0000gp/T/pip-build-h5gu9e3a/ndex/setup.py", line 16, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/Users/johnbachman/.virtualenvs/p35env/bin/../lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/1x/qf_k0tln39l637nj4jzrytgh0000gp/T/pip-build-h5gu9e3a/ndex/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1x/qf_k0tln39l637nj4jzrytgh0000gp/T/pip-build-h5gu9e3a/ndex/
```

**Comment by johnbachman** [comment]
Looks like it's working now. Thanks!

**Comment by agary-ucsd** [comment]
Hey @johnbachman, sorry I should have updated this thread to let you know.  If you run into any other issues please let us know.  Thx
