### ISSUE TITLE
BytesIO incompatibility with Python3

### ISSUE THREAD

**Issue by cthoyt** [ndexbio/ndex-python#11]
In the last 3 lines of the traceback: `BytesIO` is unable to cope with the `str` object returned by the `json.dumps`
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cthoyt/dev/pybel2cx/src/pybel2cx/__main__.py", line 14, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/cthoyt/dev/pybel2cx/src/pybel2cx/cli.py", line 71, in upload
    cx_to_ndex(cx, username=username, password=password, debug=debug)
  File "/Users/cthoyt/dev/pybel2cx/src/pybel2cx/io.py", line 63, in cx_to_ndex
    return ndex.save_new_network(cx)
  File "/usr/local/lib/python3.6/site-packages/ndex/client.py", line 253, in save_new_network
    stream = io.BytesIO(json.dumps(cx))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by dexterpratt** [comment]
Do you have the very latest version? Vlad's commit from yesterday fixed this problem for me and I was able to run save_new_network in Python 3.6

**Comment by cthoyt** [comment]
I was using current version from PyPI. I got the dev code and it works without a problem! Thanks so much @vrynkov!

**Comment by rpillich** [comment]
So this means we should push the latest DEV code to PyPi, right?

Can you guys take care of it and let me know what the new version number is so that I can update the tutorial?

Thanks
Rudi

**Comment by cthoyt** [comment]
Rudi, are you keeping your tutorial in the ndex-Python repository? I'd suggest checking out https://github.com/peritus/bumpversion so you and team can automatically keep all version strings across the repository synced

**Comment by rpillich** [comment]
Hi Charlie,
As far as I know we have a Jupiter notebook version of the tutorial in the repository… I don’t personally put my hands in the repos at all as that is not my domain!
I strongly recommend someone else in the team (Dexter, Aaron, Jing or Vlad) follows up on Charlie’s suggestion.

Thanks
Rudi

**Comment by dexterpratt** [comment]
We have it in a separate repo, but it would make more sense to locate the tutorial notebooks for all ndex-python functionality in that repo. They are in a separate repo only because of development history.

**Comment by rpillich** [comment]
Ok, who is going to take the lead for this?
Any volunteers?

R

**Comment by agary-ucsd** [comment]
I can take a look at the bumpversion project and see if it applies to our workflow.

Thanks,
Aaron Gary
Bioinformatics Software Engineer
Center for Computational Biology and Bioinformatics
School of Medicine
University of California San Diego

**Comment by rpillich** [comment]
Excellent,
Thanks Aaron!

Keep us posted using this same thread!

R
